# Generated by Django 5.2.7 on 2026-09-24 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('actor_role', models.CharField(blank=True, default='', max_length=50)),
                ('action_type', models.CharField(choices=[('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deactivated'), ('AUTH_LOGIN', 'User Logged In'), ('AUTH_LOGOUT', 'User Logged Out'), ('COURSE_CREATE', 'Course Created'), ('COURSE_UPDATE', 'Course Updated'), ('COURSE_DELETE', 'Course Deactivated'), ('SUBJECT_CREATE', 'Subject Created'), ('SUBJECT_UPDATE', 'Subject Updated'), ('SUBJECT_DELETE', 'Subject Deactivated'), ('LAB_CREATE', 'Lab Created'), ('LAB_UPDATE', 'Lab Updated'), ('LAB_DELETE', 'Lab Archived'), ('MATERIAL_UPLOAD', 'Material Uploaded'), ('MATERIAL_UPDATE', 'Material Updated'), ('MATERIAL_DELETE', 'Material Deleted'), ('ENROLLMENT_ASSIGN', 'Course Assigned'), ('SUBJECT_ASSIGN', 'Subject Assigned'), ('SETTINGS_UPDATE', 'Settings Updated'), ('OTHER', 'Other Action')], default='OTHER', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('NOTICE', 'Notice'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], default='INFO', max_length=20)),
                ('target_entity', models.CharField(blank=True, default='', help_text='Entity type, e.g. User, Lab, Course, Subject, StudyMaterial', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', help_text='ID or primary key of the modified object', max_length=100)),
                ('target_name', models.CharField(blank=True, default='', help_text='Human readable target descriptor', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Admin or user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
