# Generated by Django 5.2.7 on 2026-09-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lab_access_blocked',
            field=models.BooleanField(default=False, help_text='If True, student cannot attend, start, or submit practical labs'),
        ),
        migrations.AddField(
            model_name='user',
            name='lab_access_block_reason',
            field=models.CharField(blank=True, default='', help_text='Administrative reason explaining why lab access is blocked', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deactivated'), ('LAB_ACCESS_BLOCK', 'Lab Access Blocked'), ('LAB_ACCESS_UNBLOCK', 'Lab Access Unblocked'), ('AUTH_LOGIN', 'User Logged In'), ('AUTH_LOGOUT', 'User Logged Out'), ('COURSE_CREATE', 'Course Created'), ('COURSE_UPDATE', 'Course Updated'), ('COURSE_DELETE', 'Course Deactivated'), ('SUBJECT_CREATE', 'Subject Created'), ('SUBJECT_UPDATE', 'Subject Updated'), ('SUBJECT_DELETE', 'Subject Deactivated'), ('LAB_CREATE', 'Lab Created'), ('LAB_UPDATE', 'Lab Updated'), ('LAB_DELETE', 'Lab Archived'), ('MATERIAL_UPLOAD', 'Material Uploaded'), ('MATERIAL_UPDATE', 'Material Updated'), ('MATERIAL_DELETE', 'Material Deleted'), ('ENROLLMENT_ASSIGN', 'Course Assigned'), ('SUBJECT_ASSIGN', 'Subject Assigned'), ('SETTINGS_UPDATE', 'Settings Updated'), ('OTHER', 'Other Action')], default='OTHER', max_length=50),
        ),
    ]
