# Generated by Django 5.2.7 on 2026-09-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_labsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('attend_count', models.PositiveIntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('solved_questions_count', models.PositiveIntegerField(default=0)),
                ('total_questions_count', models.PositiveIntegerField(default=0)),
                ('first_attended_at', models.DateTimeField(auto_now_add=True)),
                ('last_attended_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='courses.lab')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_attended_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'lab'), name='unique_student_lab_score')],
            },
        ),
    ]
