# Generated by Django 5.2.7 on 2026-09-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_subjectenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='video_file',
            field=models.FileField(blank=True, help_text='Uploaded lab teaching video file', null=True, upload_to='lab_videos/'),
        ),
        migrations.AddField(
            model_name='lab',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='External teaching video URL (e.g. YouTube, Vimeo, MP4 stream)', max_length=500),
        ),
    ]
