# Generated by Django 5.2.7 on 2026-09-18 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lab_video_file_lab_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(help_text='Uploaded study material file (PDF, Word, or PPTX).', upload_to='study_materials/')),
                ('file_type', models.CharField(choices=[('PDF', 'PDF Document'), ('WORD', 'Word Document'), ('PPTX', 'PowerPoint Presentation'), ('OTHER', 'Other Document')], default='PDF', max_length=10)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(blank=True, help_text='Optional related lab for this material.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='courses.lab')),
                ('subject', models.ForeignKey(help_text='The subject this material belongs to (mandatory).', on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
