# Generated by Django 5.2.7 on 2026-09-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='setup_commands',
            field=models.TextField(blank=True, default='', help_text='CLI / Terminal commands to start or build the lab locally (e.g. docker-compose up -d)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='setup_guide',
            field=models.TextField(blank=True, default='', help_text='Step-by-step instructions for running and setting up the lab locally'),
        ),
        migrations.AddField(
            model_name='lab',
            name='source_file',
            field=models.FileField(blank=True, help_text='Lab source code archive or file (.zip, .tar.gz, etc.)', null=True, upload_to='lab_sources/'),
        ),
        migrations.AddField(
            model_name='lab',
            name='source_file_size',
            field=models.PositiveIntegerField(default=0, help_text='Size in bytes of uploaded source file'),
        ),
        migrations.AddField(
            model_name='lab',
            name='source_link',
            field=models.URLField(blank=True, default='', help_text='External source code repository or container link (e.g. GitHub, GitLab, Docker Hub)', max_length=500),
        ),
    ]
